# Δ-SNOW Calibration Configuration File (UNSCALED)

paths:
  nc_file: "/Users/jakobwerkgarner/code/mt_dsnow/calibration/calibration_data/raw_data/dsnow/Win21_calib/Win21_all.nc"
  r_script: "/Users/jakobwerkgarner/code/mt_dsnow/calibration/helpers/minimal_delta_snow_runner.R"
  output_dir: "/Users/jakobwerkgarner/code/mt_dsnow/calibration/calibration_py/L-BFGS-B/python_calib_log"

optimization:
  maxiter: 10
  PENALTY_WEIGHT: 0.01

parameters:
  # EXACT ORDER FROM R (par_delta)
  names: ["rho.max", "rho.null", "c.ov", "k.ov", "k.exp", "tau", "eta.null"]

  # UN-SCALED calibrated values
  initial:
    - 425       # rho.max
    - 100      # rho.null
    - 0.0005000005 # c.ov
    - 0.505       # k.ov
    - 0.105      # k.exp
    - 0.03      # tau
    - 5000000.0 # eta.null

  # UN-SCALED bounds (directly from R before dividing by par_scale)
  bounds:
    - [350, 500]      # rho.max
    - [70, 130]       # rho.null
    - [1e-9, 0.001]   # c.ov make sure not 9 otherwise moedel blows ups
    - [0.01, 1]      # k.ov
    - [0.01, 0.2]     # k.exp
    - [0.01, 0.06]     # tau
    - [1e6, 2e7]      # eta.null

  # SCALE FACTORS (EXACT ORDER FROM R's par_scale)
  scale: [1000, 1000, 0.001, 1, 0.1, 0.1, 1e7]

